<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('content')->insert([
            [
                'title' => 'Pulp Fiction',
                'description' => 'The lives of two mob hitmen, a boxer, a gangster, and his wife intertwine in four tales of violence and redemption.',
                'image_url' => "{{ Storage::url('images/Pulp Fiction.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Pulp Fiction.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '1994-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'The Godfather',
                'description' => 'The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.',
                'image_url' => "{{ Storage::url('images/The Godfather.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/The GodFather.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '1972-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'Inception',
                'description' => 'A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea into the mind of a CEO.',
                'image_url' => "{{ Storage::url('images/Inception.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Inception.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2010',
                'updated_at' => now(),
            ],
            [
                'title' => 'Batman: Begins',
                'description' => 'After training with his mentor, Batman begins his war on crime to free Gotham City from corruption.',
                'image_url' => "{{ Storage::url('images/Batman Begins.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Batman Begins.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2005',
                'updated_at' => now(),
            ],
            [
                'title' => 'Breaking Bad',
                'description' => 'High school chemistry teacher turned drug lord struggles with morality and survival.',
               'image_url' => "{{ Storage::url('images/Breaking Bad.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Breaking Bad.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2008',
                'updated_at' => now(),
            ],
            [
                'title' => 'The Dark Knight',
                'description' => 'The Joker creates chaos and terror in Gotham City.',
                'image_url' => "{{ Storage::url('images/The Dark Knight.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/The Dark Knight.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2008',
                'updated_at' => now(),
            ],
            [
                'title' => 'The Dark Knight Rises',
                'description' => 'Bane attacks Gotham City, forcing Bruce Wayne to don the Batman cape once again.',
                'image_url' => "{{ Storage::url('images/The Dark Knight Ries.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/The Dark Knight Ries.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2012',
                'updated_at' => now(),
            ],
           
            [
                'title' => 'Band of Brothers',
                'description' => "The series dramatizes the history of 'Easy' Company, 2nd Battalion, 506th Parachute Infantry Regiment of the 101st Airborne Division. It begins during Easy Company's paratrooper training and follows its participation in the Western Front of World War II.",
                'image_url' => "{{ Storage::url('images/Band of Brothers.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Band of Brothers.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2001-01-01',
                'updated_at' => now(),
            ],
            [
                'title' => 'Game of Thrones', 
                'description' => "Game of Thrones describes a long struggle for power between noble families while a threat looms over their kingdoms, an external enemy that destroys everything in its path: the White Walkers.",
                'image_url' => "{{ Storage::url('images/Game of Thrones.webp') }}",
                'trailer_url' => "{{ Storage::url('/videos/Game of Thrones.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2011-01-01',
                'updated_at' => now(),
            ],
            [
                'title' => 'Dexter', 
                'description' => "Dexter is a serial killer with a 'code' which directs his compulsions to kill only the guilty.",
                'image_url' => "{{ Storage::url('images/Dexter.webp') }}",
                'trailer_url' => "{{ Storage::url('/videos/Dexter.mp4) }}",
                'content_type' => 'VIP',
                'content_type' => 'Regular',
                'created_at' => '2006',
                'updated_at' => now(),
            ],
            [
                'title' => 'Peaky Blinders',
                'description' => "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby. ",
                'image_url' => "{{ Storage::url('images/Peaky Blinders.webp') }}",
                'trailer_url' => "{{ Storage::url('/videos/Peaky Blinders.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2013',
                'updated_at' => now(),
            ],
            [
                'title' => 'Friends',
                'description' => "Comedy series about a tight-knit group of friends living in Manhattan.",
                'image_url' => "{{ Storage::url('images/Friends.webp') }}",
                'trailer_url' => "{{ Storage::url('/videos/Friends.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '1994-01-01',
                'updated_at' => now(),
            ],
            [
                'title' => 'The Sopranos',
                'description' => "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state.",
                'image_url' => "{{ Storage::url('images/The Sopranos.webp') }}",
                'trailer_url' => "{{ Storage::url('/videos/The Sopranos.mp4) }}",
                'content_type' => 'VIP',
                'content_type' => 'Regular',
                'created_at' => '1999-01-01',
                'updated_at' => now(),
            ],
            [
                'title' => 'Sherlock',
                'description' => "Originally shown on the BBC, SHERLOCK adapts the classic story of Sherlock Holmes to fit into the world of modern-day London. Holmes (Benedict Cumberbatch) and Dr. John Watson (Martin Freeman) team up to solve cases involving serial killers, espionage, and bombings.",
                'image_url' => "{{ Storage::url('images/Sherlock.webp') }}",
                'trailer_url' => "{{ Storage::url('/videos/Sherlock.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2010-01-01',
                'updated_at' => now(),
            ],
            [
                'title' => 'No time to die', 
                'description' => "James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
                'image_url' => "{{ Storage::url('images/No time to die.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/No time to die.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2020',
                'updated_at' => now(),
            ],
            [
                'title' => 'Prison Break', 
                'description' => "The story revolves around a man who was sentenced to death for a crime he did not commit and his brother's elaborate plan to help him escape his death sentence.",
                'image_url' => "{{ Storage::url('images/Prison Break.webp') }}",
                'trailer_url' => "{{ Storage::url('/videos/Prison Break.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2005',
                'updated_at' => now(),
            ],
            [
                'title' => 'The Haunting of Hill House',
                'description' => "The plot alternates between two timelines, following five adult siblings whose paranormal experiences at Hill House continue to haunt them in the present day, and flashbacks depicting events leading up to the eventful night in 1992 when the family fled from the mansion.",
                'image_url' => "{{ Storage::url('images/The Haunting Of Hill House.webp') }}",
                'trailer_url' => "{{ Storage::url('/videos/The Haunting Of Hill House.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2018',
                'updated_at' => now(),
            ],
            [
                'title' => ' How I Met Your Mother',
                'description' => "How I Met Your Mother is a sitcom created initially for CBS by Carter Bays and Craig Thomas. Five friends living in New York City navigate their twenties and thirties as they try to find love, success, and purpose. The show is framed through one friend's eyes, Ted Mosby, as he retells the story of how he met his wife to his children.",
                'image_url' => "{{ Storage::url('images/How I met your Mother.webp') }}",
                'trailer_url' => "{{ Storage::url('/videos/How I met your Mother.mp4) }}",
                'created_at' => '2005',
                'updated_at' => now(),
            ],
            [
                'title' => 'The X Files',
                'description' => "The X-Files focused on the professional lives of two FBI special agents, Fox Mulder and Dana Scully, who are charged with investigating unusual and unsolved cases, known as X-Files, that involved elements of the supernatural or paranormal.",
                'image_url' => "{{ Storage::url('images/The XFiles.webp') }}",
                'trailer_url' => "{{ Storage::url('/videos/The XFiles.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '1993',
                'updated_at' => now(),
            ],
            [
                'title' => 'Fargo',
                'description' => "Fargo is a reality-based crime drama set in Minnesota in 1987, revolving around a car salesman in debt who hires two thugs to kidnap his wife.",
                'image_url' => "{{ Storage::url('images/Fargo.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Fargo.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2014-01-01 00:00:00',
                'updated_at' => now(),
            ],
           
            [
                'title' => 'The Vietnam War',
                'description' => "Visceral and immersive, the series explores the human dimensions of the war through revelatory testimony of nearly 80 witnesses from all sides.",
                'image_url' => "{{ Storage::url('images/The Vietnam War.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/The Vietnam War.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2017-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'Blindspot ',
                'description' => "Blindspot focuses on a mysterious tattooed woman who is found naked inside a travel bag in Times Square in New York City by the Federal Bureau of Investigation (FBI). ",
                'image_url' => "{{ Storage::url('images/Blindspot.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Blindspot.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2015',
                'updated_at' => now(),
            ],
            [
                'title' => '24',
                'description' => "Synopsis Counterterrorism agent Jack Bauer fights the bad guys of the world, a day at a time. ",
                'image_url' => "{{ Storage::url('images/24.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/24.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2001',
                'updated_at' => now(),
            ],
            [
                'title' => 'The Walking Dead',
                'description' => "It tells the story of a group of survivors living in a zombie apocalypse.",
                'image_url' => "{{ Storage::url('images/The Walking Dead.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/The Walking Dead.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2010',
                'updated_at' => now(),
            ],
            [
                'title' => 'The Big Bang Theory',
                'description' => "Penny moves into a Pasadena apartment across from socially awkward physicists Sheldon and Leonard, showing them life outside the lab.",
                'image_url' => "{{ Storage::url('images/The Big Bang Theory.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/The Big Bang Theory.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2007-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'Homeland',
                'description' => "A bipolar CIA operative becomes convinced a prisoner of war has been turned by al-Qaeda and is planning to attack on American soil.",
                'image_url' => "{{ Storage::url('images/Homeland.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Homeland.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2011-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'The Matrix',
                'description' => 'A computer hacker learns about the true nature of reality and his role in the war against its controllers.',
                'image_url' => "{{ Storage::url('images/The Matrix.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/The Matrix.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '1999-01-01 00:00:00',
                'updated_at' => now(),
            ],        
            [
                'title' => 'Schindler\'s List',
                'description' => 'The true story of Oskar Schindler, who saved more than a thousand Jewish refugees from the Holocaust by employing them in his factories.',
                'image_url' => "{{ Storage::url('images/Schindler's List.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Schindler's List.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '1993-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'Parasite',
                'description' => 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
                'image_url' => "{{ Storage::url('images/Parasite.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Parasite.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2019-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'Furiosa: A Mad Max Saga',
                'description' => 'Snatched from the Green Place of Many Mothers, young Furiosa falls into the hands of a great biker horde led by the warlord Dementus.',
                'image_url' => "{{ Storage::url('images/Furiosa.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Furiosa.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2024',
                'updated_at' => now(),
            ],
            [
                'title' => 'The Shawshank Redemption',
                'description' => 'Two imprisoned men bond over the years, finding solace and eventual redemption through acts of common decency.',
                'image_url' => "{{ Storage::url('images/The Shawshank Redemption.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/The Shawshank Redemption.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '1994-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'Godzilla x Kong: The New Empire',
                'description' => 'Godzilla and Kong face off as humanity uncovers their origins and mysteries on Skull Island.',
                'image_url' => "{{ Storage::url('images/Godzilla x Kong _ The New Empire.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Godzilla x Kong _ The New Empire.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2024-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'Gladiator',
                'description' => 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
                'image_url' => "{{ Storage::url('images/Gladiator.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Gladiator.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2000-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'Titanic',
                'description' => 'A young aristocrat falls in love with a kind but poor artist aboard the ill-fated Titanic.',
                'image_url' => "{{ Storage::url('images/Titanic.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Titanic.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '1997-01-01 00:00:00',
                'updated_at' => now(),
            ],
            [
                'title' => 'Kungfu Panda ',
                'description' => "It's the story about a lazy, irreverent slacker panda, named Po, who is the biggest fan of Kung Fu around.",
                'image_url' => "{{ Storage::url('images/Kungfu Panda .jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Kungfu Panda .mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2008',
                'updated_at' => now(),
            ],
            [
                'title' => 'Ben 10 Omniverse',
                'description' => 'The continuing adventures of Ben Tennyson and his new partner, Rook Blonko.',
                'image_url' => "{{ Storage::url('images/Ben 10 Omniverse.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Ben 10 Omniverse.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2024',
                'updated_at' => now(),
            ],
            [
                'title'=> 'Cây táo nở hoa',
                'description'=> 'Bộ phim kể về cuộc sống của một gia đình với năm người con, mỗi người đều có cá tính riêng biệt. Những mâu thuẫn và xung đột giữa các thành viên tạo ra nhiều tình huống cảm động, khiến khán giả không khỏi rơi nước mắt.',
                'image_url' => "{{ Storage::url('images/Cây táo nở hoa.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Cây táo nở hoa.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2021',
                'updated_at' => now(),       
            ], 
            [
                'title'=> 'Sống chung với mẹ chồng',
                'description'=> 'Câu chuyện xoay quanh cuộc sống hôn nhân của Vân (Bảo Thanh) và Thanh (Anh Dũng) khi họ sống cùng với mẹ chồng, bà Phương (NSND Lan Hương). Những mâu thuẫn và xung đột giữa mẹ chồng và nàng dâu, cùng với những vấn đề phức tạp trong mối quan hệ vợ chồng, tạo nên những tình tiết hấp dẫn và kịch tính, thu hút sự quan tâm của đông đảo người xem.',
                'image_url' => "{{ Storage::url('images/Sống chung với mẹ chồng.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Sống chung với mẹ chồng.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2017',
                'updated_at' => now(),       
            ], 
            [
                'title'=> 'Hoa hồng trên ngực trái',
                'description'=> 'Bộ phim này được coi là một trong những tác phẩm truyền hình thành công nhất khai thác chủ đề hôn nhân gia đình. Câu chuyện xoay quanh cuộc hôn nhân của Khuê và Thái, một cặp đôi gắn bó từ thời sinh viên. Tuy nhiên, sau một thời gian chung sống, mâu thuẫn giữa họ ngày càng gia tăng, đặc biệt khi một người thứ ba xuất hiện và làm rạn nứt mối quan hệ. Trong khi Khuê tìm thấy hạnh phúc mới, Thái phải đối mặt với những hậu quả của hành động của mình. ',
                'image_url' => "{{ Storage::url('images/Hoa hồng trên ngực trái.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Hoa hồng trên ngực trái.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2019',
                'updated_at' => now(),       
            ], 
            [
                'title'=> 'Về Nhà Đi Con',
                'description'=> 'Bộ phim kể về câu chuyện cảm động của gia đình ông Sơn và ba cô con gái: Thu Huệ, Anh Thư, và Ánh Dương. Khi trưởng thành, mỗi người trong số họ đều phải đối mặt với những thử thách riêng để tìm kiếm con đường của chính mình. ',
                'image_url' => "{{ Storage::url('images/Về nhà đi con.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Về nhà đi con.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2019',
                'updated_at' => now(),       
            ], 
            [
                'title'=> 'Quỳnh búp bê',
                'description'=> 'là một câu chuyện đầy bi kịch về cô gái tên Quỳnh, người sống với mẹ và người cha dượng bệnh hoạn. Khi quyết định bỏ trốn lên thành phố, Quỳnh không may bị lôi kéo vào môi trường mại dâm ngầm tại nhà hàng Thiên Thai, dẫn đến một chuỗi những sự kiện đau thương trong cuộc đời cô.',
                'image_url' => "{{ Storage::url('images/Quỳnh búp bê.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Quỳnh búp bê.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2018',
                'updated_at' => now(),       
            ],
          
            [
                'title'=> 'Gia đình mình vui bất thình lình',
                'description'=> 'là một bộ phim truyền hình Việt Nam ra mắt năm 2023, tập trung vào cuộc sống của gia đình ông Nguyễn Văn Toại  và bà Cúc cùng với ba người con trai và ba cô con dâu của họ.',
                'image_url' => "{{ Storage::url('images/Gia đình mình vui bất thình lình.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Gia đình mình vui bất thình lình.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2023',
                'updated_at' => now(),       
            ], 
            [
                'title'=> 'Kẻ ăn hồn', 'phim chieu rap',
                'description'=> 'là một bộ phim điện ảnh kinh dị Việt Nam do Trần Hữu Tấn đạo diễn. Câu chuyện diễn ra tại làng Địa Ngục, một nơi đầy bí ẩn và ám ảnh với những lời nguyền rùng rợn.',
                'image_url' => "{{ Storage::url('images/Kẻ ăn hồn.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Kẻ ăn hồn.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2023',
                'updated_at' => now(),       
            ], 
            [
                'title'=> 'Tiếng sét trong mưa',
                'description'=> 'Tiếng Sét Trong Mưa" là một bộ phim truyền hình Việt Nam thu hút sự chú ý của khán giả, lấy bối cảnh xã hội phong kiến. Câu chuyện xoay quanh mối tình đầy bi kịch giữa Thị Bình (Nhật Kim Anh), một cô hầu hiền lành và xinh đẹp, và Khải Duy (Cao Minh Đạt), một cậu Ba điển trai.',
                'image_url' => "{{ Storage::url('images/Tiếng sét trong mưa.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Tiếng sét trong mưa.mp4) }}",
                'content_type' => 'Regular',
                'created_at' => '2019',
                'updated_at' => now(),       
            ], 
            [
                'title'=> 'Người phán xử',
                'description'=> 'Bộ phim xoay quanh nhân vật Phan Quân (cố NSND Hoàng Dũng), một ông trùm xã hội ngầm khéo léo giấu mình dưới vẻ ngoài của một doanh nhân thành đạt. Ông đứng đầu tập đoàn Phan Thị, một tổ chức có vẻ ngoài hợp pháp nhưng thực chất là che giấu những hoạt động phi pháp. Cùng với các thuộc hạ trung thành, Phan Quân thực hiện nhiệm vụ "phán xử" những kẻ xấu và duy trì trật tự trong thế giới ngầm.',
                'image_url' => "{{ Storage::url('images/Người phán xử.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Người phán xử.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2020',
                'updated_at' => now(),       
            ], 
            [
                'title'=> ' Mắt biếc', 'phim chieu rap',
                'description'=> 'Bộ phim kể về mối tình đơn phương của Ngạn (Trần Nghĩa) dành cho Hà Lan (Trúc Anh). Ngạn vẫn luôn dành tình yêu cho Hà Lan dù cô có bỏ vùng quê lên thành phố và gặp gỡ nhiều người. Tuy nhiên, chuyện tình của Ngạn càng éo le hơn khi con gái của Hà Lan lớn lên cũng dành nhiều tình cảm cho anh.',
                'image_url' => "{{ Storage::url('images/Mắt biếc.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Mắt biếc.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2019',
                'updated_at' => now(),       
            ],
            [
                'title'=> 'Ròm' , 'phim chieu rap',
                'description'=> 'Bộ phim lấy bối cảnh tại một khu chung cư cũ tại Sài Gòn. Nhân vật chính là cậu bé Ròm mồ côi từ khi mới 14 tuổi. Ròm (Trần Anh Khoa) làm nghề “cò đề” để sống qua ngày nhưng cậu không bao giờ từ bỏ ước mơ đỗ vào trường trung học và làm người nổi tiếng. Cuộc sống của Ròm thay đổi khi gặp một nhóm bạn trong hoàn cảnh khó khăn. Ròm và những người bạn cùng nhau đối mặt với những chật vật, thách thức của cuộc sống.',
                'image_url' => "{{ Storage::url('images/Ròm'.jpg') }}",
                'trailer_url' => "{{ Storage::url('/videos/Ròm'.mp4) }}",
                'content_type' => 'VIP',
                'created_at' => '2020',
                'updated_at' => now(),       
            ],
          
        ]);  
    }
}
