<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContentGenreSeeder extends Seeder
{
    public function run()
    {
        DB::table('content_genre')->insert([
            [
                'content_id' => 1, // Nội dung "Example Movie 1"
                'genre_id' => 1,   // Thể loại "Action"
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 1,
                'genre_id' => 2,   // Thể loại "Comedy"
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 1, // Nội dung "Example Movie 2"
                'genre_id' => 12,   // Thể loại "Comedy"
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'content_id' => 2,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 2,
                'genre_id' => 4,  
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 2,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 3,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'content_id' => 3,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 3,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 4,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 4,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 5,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 5,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 5,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 5,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 6,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 6,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 6,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 6,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 7,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 7,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 7,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 7,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            

            [
                'content_id' => 8,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 8,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 8,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 8,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            

            [
                'content_id' => 9,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 9,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 9,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 9,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 10,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 10,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 11,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 11,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 12,
                'genre_id' => 11,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 13,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 13,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 13,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 14,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 14,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 14,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 15,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 15,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 15,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 16,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 16,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 16,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 17,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 17,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 17,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 18,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 18,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 18,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 19,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 19,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 19,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 20,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 20,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 20,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 21,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 21,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 21,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 22,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 2,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 22,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 23,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 23,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 23,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 24,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 24,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 24,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 25,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 25,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 25,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 26,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 26,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 26,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 27,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 27,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 27,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 28,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 28,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 28,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 29,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 29,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 30,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 30,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 31,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 31,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 32,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 32,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 33,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 33,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 34,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 34,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 35,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 35,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],  [
                'content_id' => 35,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 36,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 36,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],  [
                'content_id' => 36,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 37,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 37,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],  [
                'content_id' => 37,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 38,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 38,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],  
            [
                'content_id' => 38,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 39,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 39,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'content_id' => 39,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 40,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 40,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],  
            [
                'content_id' => 40,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 41,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 41,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],  [
                'content_id' => 41,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 42,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 42,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],  [
                'content_id' => 42,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 43,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 43,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],  [
                'content_id' => 43,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 44,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 44,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],  
            [
                'content_id' => 44,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 45,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 45,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 46,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 46,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 47,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 47,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 48,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 48,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 49,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 49,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 50,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 50,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 51,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'content_id' => 51,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'content_id' => 51,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 51,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 52,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'content_id' => 52,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'content_id' => 52,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 52,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 53,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'content_id' => 53,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'content_id' => 53,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 53,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 54,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'content_id' => 54,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'content_id' => 54,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 54,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 55,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 55,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 56,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 56,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 56,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 57,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 57,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 57,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 58,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 58,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 58,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 59,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 59,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 59,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 60,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 60,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 60,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 61,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 61,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 62,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 62,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 62,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 62,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 63,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 63,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 63,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 63,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 64,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 64,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 64,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 64,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 65,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 65,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 65,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 65,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 66,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 66,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 66,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 66,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 67,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 67,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 67,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 67,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 68,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 68,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 68,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 68,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 69,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 69,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 69,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 69,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 70,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 70,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 70,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 70,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 71,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 71,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 72,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 72,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 73,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 73,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 74,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 74,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 75,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 75,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 76,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 76,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 77,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 77,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 78,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 78,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 79,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 79,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 80,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 80,
                'genre_id' => 11,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 81,
                'genre_id' => 11,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 82,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 82,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 83,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 83,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 84,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 84,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 85,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 85,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 86,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 86,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 87,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 87,
                'genre_id' => 17,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 88,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 88,
                'genre_id' => 17,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 89,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 89,
                'genre_id' => 17,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 90,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 90,
                'genre_id' => 17,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 91,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 91,
                'genre_id' => 17,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 92,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 92,
                'genre_id' => 17,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 93,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 93,
                'genre_id' => 17,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 94,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 94,
                'genre_id' => 17,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 95,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 95,
                'genre_id' => 17,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 96,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 102,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 102,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 103,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 103,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 104,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 104,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 105,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 105,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 106,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 106,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 107,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 107,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 108,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 108,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 109,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 109,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 110,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 110,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 111,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 111,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 112,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 112,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 113,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 113,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 114,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 114,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 115,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 115,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 116,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 116,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 117,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 117,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 118,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 118,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 119,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 119,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 120,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 120,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 121,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 121,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 122,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 122,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 123,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 123,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 124,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 124,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 125,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 125,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 126,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 126,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 127,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 127,
                'genre_id' => 5,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 127,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 128,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 128,
                'genre_id' => 6,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 129,
                'genre_id' => 12,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 129,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 130,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 130,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 131,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 131,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 132,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 138,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 133,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 133,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 134,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 134,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 135,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 135,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 136,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 136,
                'genre_id' => 6,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 136,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 137,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 137,
                'genre_id' => 6,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 137,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 138,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 138,
                'genre_id' => 6,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 138,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 139,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 139,
                'genre_id' => 6,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 139,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 140,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 140,
                'genre_id' => 6,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 140,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 141,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 141,
                'genre_id' => 6,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 141,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 142,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 142,
                'genre_id' => 6,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 142,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 143,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 143,
                'genre_id' => 6,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 143,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 144,
                'genre_id' => 2,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 144,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 145,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 145,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 146,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 146,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 146,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 147,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 147,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 147,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'content_id' => 148,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 148,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 148,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'content_id' => 149,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 149,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 149,
                'genre_id' => 15,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 3,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 8,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'content_id' => 150,
                'genre_id' => 10,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 4,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 13,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 1,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'content_id' => 150,
                'genre_id' => 7,   
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
    }
}