<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SeasonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Season::insert([
            // Dexter
            [
                'movie_id' => Movie::where('title', 'Dexter')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of Dexter focuses on the beginning of Dexter Morgan’s journey as a blood spatter analyst for the Miami Metro Police Department.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Dexter')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of Dexter delves into Dexter’s personal struggles while the Miami Metro investigates a series of murders.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Dexter')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of Dexter deals with Dexter confronting new challenges as a serial killer while maintaining his normal life.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Dexter')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of Dexter features the infamous Trinity Killer and the impact he has on Dexter’s life.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Dexter')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of Dexter follows Dexter’s attempts to rebuild his life after the events of the previous season.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Dexter')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of Dexter introduces the Doomsday Killer and explores Dexter’s struggle with faith.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Dexter')->first()->id,
                'season_number' => 7,
                'description' => 'Season 7 of Dexter deals with the fallout of Debra discovering Dexter’s secret.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Dexter')->first()->id,
                'season_number' => 8,
                'description' => 'Season 8 of Dexter brings his story to a dramatic conclusion as he faces the ultimate consequences of his actions.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Band of Brothers')->first()->id,
                'season_number' => 1,
                'description' => 'Band of Brothers chronicles the history of "Easy" Company, from Operation Overlord through the war in Europe.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

               // The Sopranos
               [
                'movie_id' => Movie::where('title', 'The Sopranos')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of The Sopranos introduces Tony Soprano, a mob boss trying to balance his family life with his role in organized crime.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Sopranos')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of The Sopranos explores Tony’s increasing struggles with his personal and professional life as he navigates the complexities of mob politics.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Sopranos')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of The Sopranos focuses on the power struggles within the mob and Tony’s relationships with his family and associates.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Sopranos')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of The Sopranos highlights Tony’s expanding empire and the challenges he faces from both enemies and allies.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Sopranos')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of The Sopranos shows Tony dealing with the consequences of his actions and the complexities of loyalty within the mob.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Sopranos')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of The Sopranos brings resolutions to Tony’s story while exploring the psychological impact of his lifestyle.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
              // Game of Thrones
              [
                'movie_id' => Movie::where('title', 'Game of Thrones')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of Game of Thrones introduces the Stark family and the dangerous politics of Westeros.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Game of Thrones')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of Game of Thrones sees the Stark family facing new challenges as war breaks out across the realm.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Game of Thrones')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of Game of Thrones continues the brutal fight for power, culminating in the shocking Red Wedding.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Game of Thrones')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of Game of Thrones deals with the aftermath of the Red Wedding and the continuing battle for the Iron Throne.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Game of Thrones')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of Game of Thrones introduces new characters and the threat of the White Walkers as tensions rise in Westeros.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Game of Thrones')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of Game of Thrones features major revelations and the emergence of new threats as the battle for the realm continues.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Game of Thrones')->first()->id,
                'season_number' => 7,
                'description' => 'Season 7 of Game of Thrones leads to the final conflicts as the fight for power reaches its climax.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Game of Thrones')->first()->id,
                'season_number' => 8,
                'description' => 'Season 8 of Game of Thrones concludes the epic saga with intense battles and the fate of the Seven Kingdoms.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Prison Break
            [
                'movie_id' => Movie::where('title', 'Prison Break')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of Prison Break follows Michael Scofield as he plans to break his brother out of prison.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Prison Break')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of Prison Break sees the fugitives on the run, facing new dangers as they seek freedom.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Prison Break')->first()->id,
                'season_number' => 3,    'description' => 'Season 3 of Prison Break takes place in a Panamanian prison, where new challenges arise for Michael and his allies.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Prison Break')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of Prison Break involves a new mission to take down a secret organization.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Prison Break')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of Prison Break sees Michael’s return and the reunion with his brother.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // The X-Files
            [
                'movie_id' => Movie::where('title', 'The X Files')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of The X Files introduces Mulder and Scully as they investigate unexplained phenomena.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The X Files')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of The X Files continues the agents’ investigation into paranormal events and conspiracies.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The X Files')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of The X Files expands on the conspiracy theories while Mulder and Scully face new threats.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The X Files')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of The X Files continues to delve deeper into the mysteries surrounding the X-Files and their personal lives.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The X Files')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of The X Files explores the continuing fight against alien conspiracies and personal dilemmas for Mulder and Scully.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The X Files')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of The X Files presents new cases while dealing with the implications of the past seasons’ revelations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The X Files')->first()->id,
                'season_number' => 7,
                'description' => 'Season 7 of The X Files focuses on the aftermath of the conspiracy and its impact on Mulder and Scully’s lives.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The X Files')->first()->id,
                'season_number' => 8,
                'description' => 'Season 8 of The X Files introduces new characters and explores the legacy of the X-Files.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The X Files')->first()->id,
                'season_number' => 9,
                'description' => 'Season 9 of The X Files features significant changes and the ongoing quest for truth.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
          
            // Breaking Bad
            [
                'movie_id' => Movie::where('title', 'Breaking Bad')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of Breaking Bad follows Walter White’s descent into the drug trade after a terminal diagnosis.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Breaking Bad')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of Breaking Bad escalates the tension as Walter and Jesse face the consequences of their actions.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Breaking Bad')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of Breaking Bad introduces new characters and intensifies the conflict in the drug trade.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Breaking Bad')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of Breaking Bad brings Walter and Gus Fring into a deadly showdown.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Breaking Bad')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of Breaking Bad concludes Walter’s transformation and the ramifications of his choices.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Friends
            [
                'movie_id' => Movie::where('title', 'Friends')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of Friends introduces the group of friends living in New York City.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Friends')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of Friends explores the evolving relationships among the group.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Friends')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of Friends brings more comedic situations and romance.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Friends')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of Friends features new dynamics and guest appearances.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Friends')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of Friends continues the group’s ups and downs in their personal lives.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Friends')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of Friends features pivotal moments and character development.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Friends')->first()->id,
                'season_number' => 7,
                'description' => 'Season 7 of Friends explores new relationships and the complexities of love.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Friends')->first()->id,
                'season_number' => 8,
                'description' => 'Season 8 of Friends brings challenges as the characters grow older.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Friends')->first()->id,
                'season_number' => 9,
                'description' => 'Season 9 of Friends focuses on the characters’ careers and family life.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Friends')->first()->id,
                'season_number' => 10,
                'description' => 'Season 10 of Friends concludes the series with heartfelt goodbyes.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Peaky Blinders')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of Peaky Blinders...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Peaky Blinders')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of Peaky Blinders...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Peaky Blinders')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of Peaky Blinders...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Peaky Blinders')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of Peaky Blinders...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Peaky Blinders')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of Peaky Blinders...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Peaky Blinders')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of Peaky Blinders...',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        
        // Sherlock: 4 seasons

            [
                'movie_id' => Movie::where('title', 'Sherlock')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of Sherlock...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Sherlock')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of Sherlock...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Sherlock')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of Sherlock...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Sherlock')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of Sherlock...',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        
        // Blindspot: 5 seasons

            [
                'movie_id' => Movie::where('title', 'Blindspot')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of Blindspot...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Blindspot')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of Blindspot...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Blindspot')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of Blindspot...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Blindspot')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of Blindspot...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Blindspot')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of Blindspot...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        
        // 24: 9 seasons (including 8 original seasons and 1 "24: Live Another Day")
            [
                'movie_id' => Movie::where('title', '24')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of 24...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', '24')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of 24...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', '24')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of 24...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', '24')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of 24...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', '24')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of 24...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', '24')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of 24...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', '24')->first()->id,
                'season_number' => 7,
                'description' => 'Season 7 of 24...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', '24')->first()->id,
                'season_number' => 8,
                'description' => 'Season 8 of 24...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', '24')->first()->id,
                'season_number' => 9,
                'description' => '24: Live Another Day...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        
        // The Walking Dead: 11 seasons
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 7,
                'description' => 'Season 7 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 8,
                'description' => 'Season 8 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 9,
                'description' => 'Season 9 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 10,
                'description' => 'Season 10 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Walking Dead')->first()->id,
                'season_number' => 11,
                'description' => 'Season 11 of The Walking Dead...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        
        // The Big Bang Theory: 12 seasons
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 7,
                'description' => 'Season 7 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 8,
                'description' => 'Season 8 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 9,
                'description' => 'Season 9 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 10,
                'description' => 'Season 10 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 11,
                'description' => 'Season 11 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Big Bang Theory')->first()->id,
                'season_number' => 12,
                'description' => 'Season 12 of The Big Bang Theory...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // How I Met Your Mother
            [
                'movie_id' => Movie::where('title', 'How I Met Your Mother')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of How I Met Your Mother introduces Ted and his friends.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'How I Met Your Mother')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of How I Met Your Mother continues the story of Ted and his romantic pursuits.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'How I Met Your Mother')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of How I Met Your Mother brings significant developments for all characters.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'How I Met Your Mother')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of How I Met Your Mother explores new relationships and challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'How I Met Your Mother')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of How I Met Your Mother introduces changes in dynamics among friends.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'How I Met Your Mother')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of How I Met Your Mother dives deeper into personal stories and growth.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'How I Met Your Mother')->first()->id,
                'season_number' => 7,
                'description' => 'Season 7 of How I Met Your Mother continues with twists and turns in relationships.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'How I Met Your Mother')->first()->id,
                'season_number' => 8,
                'description' => 'Season 8 of How I Met Your Mother sets the stage for the final season.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'How I Met Your Mother')->first()->id,
                'season_number' => 9,
                'description' => 'Season 9 of How I Met Your Mother wraps up the series with Ted\'s journey to find love.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'The Haunting of Hill House')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of The Haunting of Hill House...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Homeland')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of Homeland...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Homeland')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of Homeland...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Homeland')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of Homeland...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Homeland')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of Homeland...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Homeland')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of Homeland...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Homeland')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of Homeland...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Homeland')->first()->id,
                'season_number' => 7,
                'description' => 'Season 7 of Homeland...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Homeland')->first()->id,
                'season_number' => 8,
                'description' => 'Season 8 of Homeland...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        
        // Ben 10: Omniverse: 8 seasons
            [
                'movie_id' => Movie::where('title', 'Ben 10: Omniverse')->first()->id,
                'season_number' => 1,
                'description' => 'Season 1 of Ben 10: Omniverse...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Ben 10: Omniverse')->first()->id,
                'season_number' => 2,
                'description' => 'Season 2 of Ben 10: Omniverse...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Ben 10: Omniverse')->first()->id,
                'season_number' => 3,
                'description' => 'Season 3 of Ben 10: Omniverse...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Ben 10: Omniverse')->first()->id,
                'season_number' => 4,
                'description' => 'Season 4 of Ben 10: Omniverse...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Ben 10: Omniverse')->first()->id,
                'season_number' => 5,
                'description' => 'Season 5 of Ben 10: Omniverse...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Ben 10: Omniverse')->first()->id,
                'season_number' => 6,
                'description' => 'Season 6 of Ben 10: Omniverse...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Ben 10: Omniverse')->first()->id,
                'season_number' => 7,
                'description' => 'Season 7 of Ben 10: Omniverse...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_id' => Movie::where('title', 'Ben 10: Omniverse')->first()->id,
                'season_number' => 8,
                'description' => 'Season 8 of Ben 10: Omniverse...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
    